### ISSUE TITLE
error in debian mongodb installation.

### ISSUE THREAD

**Issue by jambu** [edelight/chef-mongodb#257]
I am trying to install version 2.4.8. I get the following error on some runs.

```
================================================================================
Error executing action `install` on resource 'package[mongodb-10gen]'
================================================================================

Chef::Exceptions::Exec
----------------------
apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb-10gen=2.4.8 returned 100, expected 0

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/recipes/install.rb

 70: # install
 71: package node[:mongodb][:package_name] do
 72:   options packager_opts
 73:   action :install
 74:   version node[:mongodb][:package_version]
 75: end
 76: 

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/recipes/install.rb:71:in `from_file'

package("mongodb-10gen") do
  options "-o Dpkg::Options::=\"--force-confold\""
  retry_delay 2
  version "2.4.8"
  retries 0
  recipe_name "install"
  action [:install]
  cookbook_name :mongodb
  package_name "mongodb-10gen"
end

[2014-03-11T12:40:27+00:00] ERROR: Running exception handlers
[2014-03-11T12:40:27+00:00] ERROR: Exception handlers complete
[2014-03-11T12:40:27+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-03-11T12:40:27+00:00] FATAL: Chef::Exceptions::Exec: package[mongodb-10gen] (mongodb::install line 71) had an error: Chef::Exceptions::Exec: apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb-10gen=2.4.8 returned 100, expected 0
```

When I go inside the VM and execute the command I get the following error

```
vagrant@precise64:~$ sudo apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb-10gen=2.4.8
Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be DOWNGRADED:
  mongodb-10gen
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 150 not upgraded.
Need to get 87.9 MB of archives.
After this operation, 247 kB disk space will be freed.
E: There are problems and -y was used without --force-yes
```

**Comment by jamesonjlee** [comment]
did you run the recipe before? or was this not a clean machine?

The error is that you are trying to downgrade the version which isn't supported.

**Comment by jambu** [comment]
This is not a clean machine. It had 2.4.9 installed before. However When I did try a clean machine later, I got the same error.

**Comment by jambu** [comment]
Here

```
package("mongodb") do
  options "-o Dpkg::Options::=\"--force-confold\""
  retry_delay 2
  version "2.4.8"
  retries 0
  recipe_name "install"
  action [:install]
  cookbook_name :mongodb
  package_name "mongodb"
end

[2014-03-12T06:03:31+00:00] ERROR: Running exception handlers
[2014-03-12T06:03:31+00:00] ERROR: Exception handlers complete
[2014-03-12T06:03:32+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-03-12T06:03:32+00:00] FATAL: Chef::Exceptions::Exec: package[mongodb] (mongodb::install line 71) had an error: Chef::Exceptions::Exec: apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb=2.4.8 returned 100, expected 0
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
556 ~/work/vagrant/test$ vagrant ssh
Welcome to Ubuntu 12.04 LTS (GNU/Linux 3.2.0-23-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

151 packages can be updated.
68 updates are security updates.

Welcome to your Vagrant-built virtual machine.
Last login: Wed Mar 12 05:45:19 2014 from 10.0.2.2
vagrant@precise64:~$ mongo --version                
The program 'mongo' is currently not installed.  You can install it by typing:
sudo apt-get install mongodb-clients
```

**Comment by jeremyolliver** [comment]
The other reason that apt commands can return 100, is if another process has locked the package management system, for example, if `apt-get update` is being run simultaneously. I'd recommend running the command yourself, to see what the error output is.

**Comment by jambu** [comment]
The error output is seen in my first comment

```
E: There are problems and -y was used without --force-yes
```

**Comment by jspiewak** [comment]
Are you saying that on the clean machine which should have had mongo 2.4.9 installed, that your error message was a problem about downgrading?

If not, please include the entire message, not just the last line saying that there were problems.

**Comment by jspiewak** [comment]
Also, what version of the cookbook are you using?

**Comment by jambu** [comment]
Sorry for not being clear in the previous comment.
I am using version 0.15.0
Now I set up a separate vagrant box just with apt(2.3.9) and mongodb(0.15.0)

```
Generating chef JSON and uploading...
Running chef-solo...
stdin: is not a tty
[2014-03-12T13:10:03+00:00] INFO: *** Chef 10.14.2 ***
[2014-03-12T13:10:04+00:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[mongodb]"] from JSON
[2014-03-12T13:10:04+00:00] INFO: Run List is [recipe[apt], recipe[mongodb]]
[2014-03-12T13:10:04+00:00] INFO: Run List expands to [apt, mongodb]
[2014-03-12T13:10:04+00:00] INFO: Starting Chef Run for precise64
[2014-03-12T13:10:04+00:00] INFO: Running start handlers
[2014-03-12T13:10:04+00:00] INFO: Start handlers complete.
[2014-03-12T13:10:04+00:00] WARN: encrypted_data_bag_Secret is set but file does not exist. Unsetting
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/definitions/mongodb.rb:158: warning: Object#type is deprecated; use Object#class
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/definitions/mongodb.rb:195: warning: Object#type is deprecated; use Object#class
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/definitions/mongodb.rb:224: warning: Object#type is deprecated; use Object#class
[2014-03-12T13:10:51+00:00] INFO: execute[apt-get-update] ran successfully
[2014-03-12T13:10:56+00:00] INFO: package[update-notifier-common] sending run action to execute[apt-get-update] (immediate)
[2014-03-12T13:11:04+00:00] INFO: execute[apt-get-update] ran successfully
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local] created directory /var/cache/local
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local] owner changed to 0
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local] group changed to 0
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local] mode changed to 755
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local/preseeding] created directory /var/cache/local/preseeding
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local/preseeding] owner changed to 0
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local/preseeding] group changed to 0
[2014-03-12T13:11:04+00:00] INFO: directory[/var/cache/local/preseeding] mode changed to 755
[2014-03-12T13:11:04+00:00] INFO: file[/etc/default/mongodb] owner changed to 0
[2014-03-12T13:11:04+00:00] INFO: file[/etc/default/mongodb] group changed to 0
[2014-03-12T13:11:04+00:00] INFO: file[/etc/default/mongodb] mode changed to 644
[2014-03-12T13:11:04+00:00] INFO: file[/etc/default/mongodb] created file /etc/default/mongodb
[2014-03-12T13:11:04+00:00] INFO: template[/etc/mongodb.conf] updated content
[2014-03-12T13:11:04+00:00] INFO: template[/etc/mongodb.conf] owner changed to 0
[2014-03-12T13:11:04+00:00] INFO: template[/etc/mongodb.conf] group changed to 0
[2014-03-12T13:11:04+00:00] INFO: template[/etc/mongodb.conf] mode changed to 644
[2014-03-12T13:11:05+00:00] INFO: template[/etc/init/mongodb.conf] updated content
[2014-03-12T13:11:05+00:00] INFO: template[/etc/init/mongodb.conf] owner changed to 0
[2014-03-12T13:11:05+00:00] INFO: template[/etc/init/mongodb.conf] group changed to 0
[2014-03-12T13:11:05+00:00] INFO: template[/etc/init/mongodb.conf] mode changed to 644
[2014-03-12T13:11:05+00:00] INFO: template[/etc/init/mongodb.conf] not queuing delayed action restart on service[mongodb] (delayed), as it's already been queued

================================================================================
Error executing action `install` on resource 'package[mongodb]'
================================================================================

Chef::Exceptions::Exec
----------------------
apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb=2.4.8 returned 100, expected 0

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/recipes/install.rb

 70: # install
 71: package node[:mongodb][:package_name] do
 72:   options packager_opts
 73:   action :install
 74:   version node[:mongodb][:package_version]
 75: end
 76: 

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/recipes/install.rb:71:in `from_file'

package("mongodb") do
  options "-o Dpkg::Options::=\"--force-confold\""
  retry_delay 2
  version "2.4.8"
  retries 0
  recipe_name "install"
  action [:install]
  cookbook_name :mongodb
  package_name "mongodb"
end

[2014-03-12T13:11:05+00:00] ERROR: Running exception handlers
[2014-03-12T13:11:05+00:00] ERROR: Exception handlers complete
[2014-03-12T13:11:05+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2014-03-12T13:11:05+00:00] FATAL: Chef::Exceptions::Exec: package[mongodb] (mongodb::install line 71) had an error: Chef::Exceptions::Exec: apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb=2.4.8 returned 100, expected 0
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

So I go into the VM,

```
vagrant@precise64:~$ mongo --version
The program 'mongo' is currently not installed.  You can install it by typing:
sudo apt-get install mongodb-clients
```

So I execute the cmd which threw the error
And voila

```
vagrant@precise64:~$ sudo apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb=2.4.8 
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.4.8' for 'mongodb' was not found
```

I will close the issue. Thanks for your help. I wanted to get the same setup as production, guess I will go with 2.4.9. Should not make a big difference.

**Comment by jambu** [comment]
I wanted to check in the VM if it creates 2.4.9, but it threw the same error

```
vagrant@precise64:~$ sudo apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb=2.4.9
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '2.4.9' for 'mongodb' was not found
```

If I give the command without version like 

```
vagrant@precise64:~$ sudo apt-get -q -y -o Dpkg::Options::="--force-confold" install mongodb
```

it proceeds to install.

Do you know what is the correct format to give the version ?

EDIT: Ignore the question, apt is not supporting the latest version.

**Comment by jspiewak** [comment]
Try using the 10gen repo recipe.
