### ISSUE TITLE
0.15.1 searches for nodes with mongodb_is_replicaset attributes, but nothing sets the attrbute

### ISSUE THREAD

**Issue by gswallow** [edelight/chef-mongodb#273]
definitions/mongodb checks for the node.mongodb_is_replicaset attribute, which doesn't exist on MongoDB nodes configured by the mongdb cookbook?  Won't that result in replica sets not being set up?

Also, I don't understand why the mongodb cookbook needs specific versions of other cookbooks, which conflict with everything else I have in my repository (e.g. runit).

Beyond that, for some reason, node['mongodb']['cluster_name'] is showing up as nil and breaking Chef search, which is pissing me off and is the reason I tried 0.15.1 to begin with.  Harumph.
## RuntimeError

nil nil "default" "qa1" 
## Cookbook Trace:

  /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:202:in `block in from_file'
  /var/chef/cache/cookbooks/mongodb/recipes/replicaset.rb:27:in`from_file'
  /var/chef/cache/cookbooks/ascent-wrappers/recipes/mongodb_install.rb:17:in `from_file'
  /var/chef/cache/cookbooks/ascent-wrappers/recipes/mongodb.rb:4:in`from_file'
## Relevant File Content:

/var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:

195:      notifies :create, 'ruby_block[config_replicaset]' if new_resource.is_replicaset && new_resource.auto_configure_replicaset
196:      notifies :create, 'ruby_block[config_sharding]', :immediately if new_resource.is_mongos && new_resource.auto_configure_sharding
197:        # we don't care about a running mongodb service in these cases, all we need is stopping it
198:      ignore_failure true if new_resource.name == 'mongodb'
199:    end
200:  
201:    # Fuck.
202>>   raise("#{new_resource.replicaset['mongodb_is_replicaset'].inspect} " +
203:          "#{new_resource.replicaset['mongodb']['cluster_name'].inspect} " +
204:          "#{new_resource.replicaset['mongodb']['shard_name'].inspect} " +
205:          "#{new_resource.replicaset.chef_environment.inspect} ")
206:  
207:    # replicaset
208:    if new_resource.is_replicaset && new_resource.auto_configure_replicaset
209:      rs_nodes = search(
210:        :node,
211:        "mongodb_cluster_name:#{new_resource.replicaset['mongodb']['cluster_name']} AND \

**Comment by josephholsten** [comment]
This is relevant to the node attribute isolation of #221

**Comment by jamesonjlee** [comment]
*apt -> due to a bug fix
*yum -> due to 3.0 chef11, and new repository configurations
*runit -> I believe a bug fix

otherwise yeah, should be fixed by changes coming. (re-open to mark when 221 goes through)
