### ISSUE TITLE
0.16.0 CentOS 6.5 chef_gem[bson_ext] failed if gcc not instaled

### ISSUE THREAD

**Issue by AlexAkulov** [edelight/chef-mongodb#277]
I want to install mongodb replicaset on a clean CentOS 6.5
I'm launching it and then get a chef-client error:

```
Gem::Installer::ExtensionBuildError
-----------------------------------
ERROR: Failed to build gem native extension.

        /opt/chef/embedded/bin/ruby extconf.rb
checking for asprintf()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.
```

I'm making "yum install gcc"
Launching cheif-client and it works all right

**Comment by jspiewak** [comment]
What recipe(s) are you running?
Have you installed build-essentials?

**Comment by AlexAkulov** [comment]
My Run List contains only mongodb::replicaset recipe. All parameters are set via JSON.
I do not use Cookbook build-essentials, if it is obligatory, then why it is not mentioned in dependencies of this file: metadata.rb?

**Comment by jspiewak** [comment]
It may need to be.

Unfortunately right now the replicaset recipe is not being tested by kitchen because it performs a search to determine what nodes should be in the replicaset before using the bson gem, so I am trying to reproduce on CentOS 6.5....

**Comment by jspiewak** [comment]
Reproduced, working on a fix....
Meantime you can either install build-essentials or turn off auto configure replica set

**Comment by jspiewak** [comment]
@AlexAkulov does master after the merge of #280 solve your issue?

**Comment by moreandres** [comment]
This issue is also happening with current Ubuntu Server LTS, not only in rhel-based systems.

**Comment by jspiewak** [comment]
`kitchen test replicaset-ubuntu-1204` works just fine for me.
Could you provide more details @moreandres ?

**Comment by st-h** [comment]
I think I encountered the same issue on a Ubuntu 12.04. Adding the build-essentials cookbook fixed it. Sorry, can't provide more details right now, but will see to try it within the next days and keep you updated if needed.

**Comment by st-h** [comment]
I finally got around to give this another try. Here is the output from /var/chef/cache/chef-stacktrace.out

```
Generated at 2014-04-19 17:20:23 +0200
Gem::Installer::ExtensionBuildError: chef_gem[bson_ext] (mongodb::mongo_gem line 10) had an error: Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

        /opt/chef/embedded/bin/ruby extconf.rb
checking for asprintf()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/opt/chef/embedded/bin/ruby
/opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:461:in `try_link0'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:476:in `try_link'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:619:in `try_func'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:894:in `block in have_func'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
        from /opt/chef/embedded/lib/ruby/1.9.1/mkmf.rb:893:in `have_func'
        from extconf.rb:3:in `<main>'


Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/bson_ext-1.10.0 for inspection.
Results logged to /opt/chef/embedded/lib/ruby/gems/1.9.1/gems/bson_ext-1.10.0/ext/cbson/gem_make.out

/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:556:in `rescue in block in build_extensions'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:534:in `block in build_extensions'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:509:in `each'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:509:in `build_extensions'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:180:in `install'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:297:in `block in install'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in `each_with_index'
/opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/dependency_installer.rb:270:in `install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package/rubygems.rb:201:in `block (2 levels) in install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package/rubygems.rb:224:in `with_correct_verbosity'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package/rubygems.rb:200:in `block in install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package/rubygems.rb:110:in `with_gem_sources'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package/rubygems.rb:199:in `install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package/rubygems.rb:511:in `install_package'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package.rb:82:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/why_run.rb:52:in `call'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider.rb:155:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider/package.rb:80:in `action_install'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/provider.rb:120:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/resource.rb:625:in `run_action'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/resource/chef_gem.rb:47:in `block in after_created'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/resource/chef_gem.rb:46:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/resource/chef_gem.rb:46:in `after_created'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:126:in `build_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:86:in `declare_resource'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/dsl/recipe.rb:42:in `method_missing'
/var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:10:in `block in from_file'
/var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:9:in `each'
/var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:9:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_version.rb:237:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:151:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:132:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:131:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:131:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/mongodb/recipes/replicaset.rb:24:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_version.rb:237:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:151:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:132:in `block in include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:131:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:131:in `include_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/dsl/include_recipe.rb:26:in `include_recipe'
/var/chef/cache/cookbooks/wrapper-mongodb/recipes/default.rb:36:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/mixin/from_file.rb:30:in `from_file'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/cookbook_version.rb:237:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:151:in `load_recipe'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:139:in `block in compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:137:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:137:in `compile_recipes'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:74:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context.rb:86:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/policy_builder/expand_node_object.rb:75:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:252:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:413:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:200:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:194:in `fork'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/client.rb:194:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application.rb:215:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application/client.rb:314:in `block in run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application/client.rb:306:in `loop'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application/client.rb:306:in `run_application'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:23:in `load'
/usr/bin/chef-client:23:in `<main>'
(END)

```

In case it's needed some more output from stdout:

```
Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:10:in `block in from_file'
  /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:9:in `each'
  /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:9:in `from_file'
  /var/chef/cache/cookbooks/mongodb/recipes/replicaset.rb:24:in `from_file'
  /var/chef/cache/cookbooks/wrapper-mongodb/recipes/default.rb:36:in `from_file'


Relevant File Content:
----------------------
/var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:

  3:  gcc = package 'gcc' do
  4:    action :nothing
  5:    only_if { platform_family?('rhel') }
  6:  end
  7:  gcc.run_action(:install)
  8:  
  9:  node['mongodb']['ruby_gems'].each do |gem, version|
 10>>   chef_gem gem do
 11:      version version
 12:    end
 13:  end
 14:  
```

This usually goes away if I install build essentials first. This should be against master, unless berks has fooled me...

**Comment by josephholsten** [comment]
should be easy enough to resolve either by either:
- adding a dependency of `build-dependency`
- catching the the exception to add an actually useful error before rethrowing the exception

I prefer the second, since the build-dependency is occasionally unnecessary for using this cookbook.

**Comment by jamesonjlee** [comment]
well, we should do meta for build-essentials (if we also intend to open the door for src building).

As much as I don't need both apt and yum in my repo chef does pull them both down, so if the gem needs to be built from scratch we should put them in as a dependency.
