### ISSUE TITLE
Is there a way to update the admin password?

### ISSUE THREAD

**Issue by miguelaferreira** [edelight/chef-mongodb#327]
Once I've installed mongo I can't change the admin password because admin cannot authenticate with the new password in order to update it.

**Comment by jamesonjlee** [comment]
yeah we should use `current_resource` to store last-run-state.

**Comment by cjhubert** [comment]
Hmm, I've just been looking at the `current_resource` docs and am not sure how we would accomplish that in this instance. I might be missing something, it looks like I'd have to get the current password from somewhere with `load_current_resource`.

Maybe instead we should separate the admin credentials used to authenticate with the database from the admin created. So you would change the admin user credentials, then have to update the configuration so the attributes used to authenticate with the database were the new ones?

**Comment by miguelaferreira** [comment]
@ceejh what you propose seems the most simple solution. As an example, see the nexus cookbook README (https://github.com/RiotGames/nexus-cookbook). They define `default_admin` and `updated_admin` to accomplish the update. As long as the default is kept in synch with the current credentials it should always be possible to set updated credentials.

**Comment by cjhubert** [comment]
@miguelaferreira Would you please take a look at [this branch](https://github.com/ceejh/chef-mongodb/compare/admin-user-update) and see if the changes would meet your needs for this issue for me? Thanks.

**Comment by miguelaferreira** [comment]
@ceejh sorry for the long silence. Starting tests on your branch now.

**Comment by miguelaferreira** [comment]
@ceejh my first test was to have chef-client run twice with the same attributes and that is failing with the following message: 

```
Running handlers:
[2014-09-22T11:28:25+02:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-22T11:28:25+02:00] ERROR: Exception handlers complete
[2014-09-22T11:28:25+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 5.718522054 seconds
[2014-09-22T11:28:25+02:00] ERROR: mongodb_user[mongoadmin] (mongodb::user_management line 14) had an error: Mongo::OperationFailure: Database command 'createUser' failed: not authorized on admin to execute command { createUser: "mongoadmin", pwd: "xxx", digestPassword: false, writeConcern: { w: 1 }, roles: [ "userAdminAnyDatabase", "dbAdminAnyDatabase" ] }
[2014-09-22T11:28:25+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

The attributes I've set are:

```
 default['mongodb']['admin']['username'] = 'mongoadmin'
 default['mongodb']['admin']['password'] = 'admin123'
 default['mongodb']['authentication']['username'] = 'mongoadmin'
 default['mongodb']['authetication']['password'] = 'admin123'
 default['mongodb']['config']['auth'] = true
```

The recipes I've added to the runlist are:

```
include_recipe 'mongodb::default'
include_recipe 'mongodb::user_management'
```

The full output from the chef-client error:

```
    ================================================================================
    Error executing action `add` on resource 'mongodb_user[mongoadmin]'
    ================================================================================

    Mongo::OperationFailure
    -----------------------
    Database command 'createUser' failed: not authorized on admin to execute command { createUser: "mongoadmin", pwd: "xxx", digestPassword: false, writeConcern: { w: 1 }, roles: [ "userAdminAnyDatabase", "dbAdminAnyDatabase" ] }

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/mongodb/providers/user.rb:34:in `add_user'
    /var/chef/cache/cookbooks/mongodb/providers/user.rb:71:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/mongodb/recipes/user_management.rb

     14:   mongodb_user user['username'] do
     15:     password user['password']
     16:     roles user['roles']
     17:     database user['database']
     18:     connection node['mongodb']
     19:     action :add
     20:   end
     21: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/mongodb/recipes/user_management.rb:14:in `block in from_file'

    mongodb_user("mongoadmin") do
      action [:add]
      retries 0
      retry_delay 2
      guard_interpreter :default
      cookbook_name "mongodb"
      recipe_name "user_management"
      password "admin123"
      roles ["userAdminAnyDatabase", "dbAdminAnyDatabase"]
      database "admin"
      connection {"client_roles"=>[], "cluster_name"=>nil, "shard_name"=>"default", "replica_arbiter_only"=>false, "replica_build_indexes"=>true, "replica_hidden"=>false, "replica_slave_delay"=>0, "replica_priority"=>1, "replica_tags"=>{}, "replica_votes"=>1, "auto_configure"=>{"replicaset"=>true, "sharding"=>true}, "configserver_url"=>nil, "root_group"=>"root", "user"=>"mongod", "group"=>"mongod", "init_dir"=>"/etc/init.d", "init_script_template"=>"redhat-mongodb.init.erb", "sysconfig_file"=>"/etc/sysconfig/mongodb", "sysconfig_file_template"=>"mongodb.sysconfig.erb", "dbconfig_file_template"=>"mongodb.conf.erb", "dbconfig_file"=>"/etc/mongodb.conf", "package_name"=>"mongodb-org", "package_version"=>nil, "default_init_name"=>"mongod", "instance_name"=>"mongod", "install_method"=>"mongodb-org", "is_replicaset"=>nil, "is_shard"=>nil, "is_configserver"=>nil, "reload_action"=>"restart", "template_cookbook"=>"mongodb", "key_file_content"=>nil, "ruby_gems"=>{"mongo"=>nil, "bson_ext"=>nil}, "config"=>{"port"=>27017, "bind_ip"=>"0.0.0.0", "logpath"=>"/var/log/mongodb/mongodb.log", "logappend"=>true, "fork"=>true, "dbpath"=>"/var/lib/mongodb", "nojournal"=>false, "rest"=>false, "smallfiles"=>false, "oplogSize"=>nil, "replSet"=>nil, "auth"=>true}, "mms_agent"=>{"api_key"=>nil, "package_url"=>"https://mms.mongodb.com/download/agent/%{agent_type}/mongodb-mms-%{agent_type}-agent", "monitoring"=>{"version"=>"2.2.0.70-1", "mmsApiKey"=>nil, "mmsBaseUrl"=>"https://mms.mongodb.com", "configCollectionsEnabled"=>true, "configDatabasesEnabled"=>true, "throttlePassesShardChunkCounts"=>10, "throttlePassesDbstats"=>20, "throttlePassesOplog"=>10, "disableProfileDataCollection"=>false, "disableGetLogsDataCollection"=>false, "disableLocksAndRecordStatsDataCollection"=>false, "enableMunin"=>true, "useSslForAllConnections"=>false, "sslRequireValidServerCertificates"=>false}, "backup"=>{"version"=>"2.1.0.106-1", "mmsApiKey"=>nil, "mothership"=>"api-backup.mongodb.com", "https"=>true, "sslRequireValidServerCertificates"=>false}, "user"=>"mongodb-mms-agent", "group"=>"mongodb-mms-agent"}, "sysconfig"=>{"DAEMON"=>"/usr/bin/$NAME", "DAEMON_USER"=>"mongod", "DAEMON_OPTS"=>"--config /etc/mongodb.conf", "CONFIGFILE"=>"/etc/mongodb.conf", "ENABLE_MONGODB"=>"yes", "DAEMONUSER"=>"mongod", "ENABLE_MONGOD"=>"yes", "ENABLE_MONGO"=>"yes"}, "ulimit"=>{"fsize"=>"unlimited", "cpu"=>"unlimited", "as"=>"unlimited", "nofile"=>64000, "rss"=>"unlimited", "nproc"=>32000}, "authentication"=>{"username"=>"mongoadmin", "password"=>"admin"}, "admin"=>{"username"=>"mongoadmin", "password"=>"admin123", "roles"=>["userAdminAnyDatabase", "dbAdminAnyDatabase"], "database"=>"admin"}, "users"=>[], "authetication"=>{"password"=>"admin123"}}
      username "mongoadmin"
    end


Running handlers:
[2014-09-22T11:28:25+02:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-22T11:28:25+02:00] ERROR: Exception handlers complete
[2014-09-22T11:28:25+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 5.718522054 seconds
[2014-09-22T11:28:25+02:00] ERROR: mongodb_user[mongoadmin] (mongodb::user_management line 14) had an error: Mongo::OperationFailure: Database command 'createUser' failed: not authorized on admin to execute command { createUser: "mongoadmin", pwd: "xxx", digestPassword: false, writeConcern: { w: 1 }, roles: [ "userAdminAnyDatabase", "dbAdminAnyDatabase" ] }
[2014-09-22T11:28:25+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by cjhubert** [comment]
It looks like you have a typo in `['authetication']` for the password. The connection attribute in the logs shows this because it's still using the default password of `admin` for authentication.

This kind of points out that the system might have some flaws in over-complicating things with two variables though... (also, it kind of sucks that all the config values are in the connection object in the logs since that might lead people to posting their passwords).

**Comment by miguelaferreira** [comment]
You are right! It was the typo.
BTW I've copied the attribute name from the updated README.md. So you will find the typo there as well (line 249).

After correcting te typo, my initial test passed. And the following test where I update te password also passed. (I could not authenticate with the old password, and I could authenticate with the new password.)

I ran another test, which was to re-run chef-client without updating the cookbook attributes and that passed too because the chef-client run failed (as expected).

Finally, I've updated the attributes and ran chef-client again, which finished without problems.

All-in-all seems good to me.

I do understand your point about having an extra attribute, but I do not see a better way to do this. You either have an extra attribute or an extra value in a data bag/vault. Either way the risk of making a typo is there. I do think that the typo should be easily caught by testing (just like in this case).

Thanks for the effort.

**Comment by cjhubert** [comment]
Ah, completely my fault for making the typo. I'm glad you followed the instructions to find it though! I'll update it and make a PR soon (hopefully). I've kind of made this part of another thing [I was working on](https://github.com/ceejh/chef-mongodb/compare/users-in-replicasets) to get the user management stuff working in replicaset / sharded instances.

**Comment by miguelaferreira** [comment]
Cool! I'm not yet using the HA features of mongodb but will soon. Let me know if you need help testing your stuff because I should have an infrastructure ready for that soon.
