### ISSUE TITLE
mongo_gem needs make package

### ISSUE THREAD

**Issue by runningman84** [edelight/chef-mongodb#372]
Please install the make package before building an extension:

```
==> shard11: chef_gem[bson_ext] (mongodb::mongo_gem line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> shard11: ---- Begin output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: STDOUT: Building native extensions.  This could take a while...
==> shard11: STDERR: ERROR:  Error installing bson_ext:
==> shard11:    ERROR: Failed to build gem native extension.
==> shard11: 
==> shard11:     /opt/chef/embedded/bin/ruby -r ./siteconf20150304-10675-1bhk51p.rb extconf.rb
==> shard11: checking for asprintf()... yes
==> shard11: checking for ruby/st.h... yes
==> shard11: checking for ruby/regex.h... yes
==> shard11: checking for ruby/encoding.h... yes
==> shard11: creating Makefile
==> shard11: 
==> shard11: make "DESTDIR=" clean
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make "DESTDIR="
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make failed, exit code 127
==> shard11: 
==> shard11: Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bson_ext-1.12.0 for inspection.
==> shard11: Results logged to /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/bson_ext-1.12.0/gem_make.out
==> shard11: ---- End output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: Ran /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" returned 1
==> shard11: 
==> shard11: Cookbook Trace:
==> shard11: ---------------
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:20:in `block in from_file'
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:19:in `each'
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:19:in `from_file'
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/replicaset.rb:24:in `from_file'
==> shard11: 
==> shard11: Relevant File Content:
==> shard11: ----------------------
==> shard11: /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:
==> shard11: 
==> shard11:  13:  end 
==> shard11:  14:  
==> shard11:  15:  package sasldev_pkg do
==> shard11:  16:    action :nothing
==> shard11:  17:  end.run_action(:install)
==> shard11:  18:  
==> shard11:  19:  node['mongodb']['ruby_gems'].each do |gem, version|
==> shard11:  20>>   chef_gem gem do
==> shard11:  21:      version version
==> shard11:  22:    end
==> shard11:  23:  end
==> shard11:  24:  
==> shard11: 
==> shard11: [2015-03-04T16:20:34+00:00] ERROR: Running exception handlers
==> shard11: [2015-03-04T16:20:34+00:00] ERROR: Exception handlers complete
==> shard11: [2015-03-04T16:20:34+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> shard11: [2015-03-04T16:20:34+00:00] ERROR: chef_gem[bson_ext] (mongodb::mongo_gem line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> shard11: ---- Begin output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: STDOUT: Building native extensions.  This could take a while...
==> shard11: STDERR: ERROR:  Error installing bson_ext:
==> shard11:    ERROR: Failed to build gem native extension.
==> shard11: 
==> shard11:     /opt/chef/embedded/bin/ruby -r ./siteconf20150304-10675-1bhk51p.rb extconf.rb
==> shard11: checking for asprintf()... yes
==> shard11: checking for ruby/st.h... yes
==> shard11: checking for ruby/regex.h... yes
==> shard11: checking for ruby/encoding.h... yes
==> shard11: creating Makefile
==> shard11: 
==> shard11: make "DESTDIR=" clean
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make "DESTDIR="
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make failed, exit code 127
==> shard11: 
==> shard11: Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bson_ext-1.12.0 for inspection.
==> shard11: Results logged to /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/bson_ext-1.12.0/gem_make.out
==> shard11: ---- End output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: Ran /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" returned 1
==> shard11: [2015-03-04T16:20:34+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
==> shard11: chef_gem[bson_ext] (mongodb::mongo_gem line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> shard11: ---- Begin output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: STDOUT: Building native extensions.  This could take a while...
==> shard11: STDERR: ERROR:  Error installing bson_ext:
==> shard11:    ERROR: Failed to build gem native extension.
==> shard11: 
==> shard11:     /opt/chef/embedded/bin/ruby -r ./siteconf20150304-10675-1bhk51p.rb extconf.rb
==> shard11: checking for asprintf()... yes
==> shard11: checking for ruby/st.h... yes
==> shard11: checking for ruby/regex.h... yes
==> shard11: checking for ruby/encoding.h... yes
==> shard11: creating Makefile
==> shard11: 
==> shard11: make "DESTDIR=" clean
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make "DESTDIR="
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make failed, exit code 127
==> shard11: 
==> shard11: Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bson_ext-1.12.0 for inspection.
==> shard11: Results logged to /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/bson_ext-1.12.0/gem_make.out
==> shard11: ---- End output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: Ran /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" returned 1
==> shard11: 
==> shard11: Cookbook Trace:
==> shard11: ---------------
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:20:in `block in from_file'
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:19:in `each'
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:19:in `from_file'
==> shard11:   /var/chef/cache/cookbooks/mongodb/recipes/replicaset.rb:24:in `from_file'
==> shard11: 
==> shard11: Relevant File Content:
==> shard11: ----------------------
==> shard11: /var/chef/cache/cookbooks/mongodb/recipes/mongo_gem.rb:
==> shard11: 
==> shard11:  13:  end 
==> shard11:  14:  
==> shard11:  15:  package sasldev_pkg do
==> shard11:  16:    action :nothing
==> shard11:  17:  end.run_action(:install)
==> shard11:  18:  
==> shard11:  19:  node['mongodb']['ruby_gems'].each do |gem, version|
==> shard11:  20>>   chef_gem gem do
==> shard11:  21:      version version
==> shard11:  22:    end
==> shard11:  23:  end
==> shard11:  24:  
==> shard11: 
==> shard11: [2015-03-04T16:20:34+00:00] ERROR: Running exception handlers
==> shard11: [2015-03-04T16:20:34+00:00] ERROR: Exception handlers complete
==> shard11: [2015-03-04T16:20:34+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> shard11: [2015-03-04T16:20:34+00:00] ERROR: chef_gem[bson_ext] (mongodb::mongo_gem line 20) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> shard11: ---- Begin output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: STDOUT: Building native extensions.  This could take a while...
==> shard11: STDERR: ERROR:  Error installing bson_ext:
==> shard11:    ERROR: Failed to build gem native extension.
==> shard11: 
==> shard11:     /opt/chef/embedded/bin/ruby -r ./siteconf20150304-10675-1bhk51p.rb extconf.rb
==> shard11: checking for asprintf()... yes
==> shard11: checking for ruby/st.h... yes
==> shard11: checking for ruby/regex.h... yes
==> shard11: checking for ruby/encoding.h... yes
==> shard11: creating Makefile
==> shard11: 
==> shard11: make "DESTDIR=" clean
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make "DESTDIR="
==> shard11: sh: 1: make: not found
==> shard11: 
==> shard11: make failed, exit code 127
==> shard11: 
==> shard11: Gem files will remain installed in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/bson_ext-1.12.0 for inspection.
==> shard11: Results logged to /opt/chef/embedded/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0/bson_ext-1.12.0/gem_make.out
==> shard11: ---- End output of /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" ----
==> shard11: Ran /opt/chef/embedded/bin/gem install bson_ext -q --no-rdoc --no-ri -v "1.12.0" returned 1
==> shard11: [2015-03-04T16:20:34+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by runningman84** [comment]
this could be a fix:
https://github.com/edelight/chef-mongodb/pull/370
