### ISSUE TITLE
DEBUG: apt_package[mongodb] candidate version for mongodb is (none)

### ISSUE THREAD

**Issue by lmilbaum** [edelight/chef-mongodb#417]
I would like to install mongodb 3.2.7 on Ubuntu 16.04.
Specified in the file: attributes/default.rb
override[:mongodb][:package_version] = '3.2.7'

Output:
169.46.88.66   * apt_package[mongodb] action install
169.46.88.66     * No candidate version available for mongodb
169.46.88.66     ================================================================================
169.46.88.66     Error executing action `install` on resource 'apt_package[mongodb]'
169.46.88.66     ================================================================================
169.46.88.66     
169.46.88.66     Chef::Exceptions::Package
169.46.88.66     -------------------------
169.46.88.66     No candidate version available for mongodb
169.46.88.66     
169.46.88.66     Cookbook Trace:
169.46.88.66     ---------------
169.46.88.66     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
169.46.88.66     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
169.46.88.66     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
169.46.88.66     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
169.46.88.66     /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
169.46.88.66     
169.46.88.66     Resource Declaration:
169.46.88.66     ---------------------
169.46.88.66     # In /var/chef/cache/cookbooks/mongodb/recipes/install.rb
169.46.88.66     
169.46.88.66      77: package node[:mongodb][:package_name] do
169.46.88.66      78:   options packager_opts
169.46.88.66      79:   action :install
169.46.88.66      80:   version node[:mongodb][:package_version]
169.46.88.66      81: end
169.46.88.66      82: 
169.46.88.66     
169.46.88.66     Compiled Resource:
169.46.88.66     ------------------
169.46.88.66     # Declared in /var/chef/cache/cookbooks/mongodb/recipes/install.rb:77:in `from_file'
169.46.88.66     
169.46.88.66     apt_package("mongodb") do
169.46.88.66       package_name "mongodb"
169.46.88.66       action [:install]
169.46.88.66       retries 0
169.46.88.66       retry_delay 2
169.46.88.66       default_guard_interpreter :default
169.46.88.66       declared_type :package
169.46.88.66       cookbook_name "mongodb"
169.46.88.66       recipe_name "install"
169.46.88.66       options "-o Dpkg::Options::=\"--force-confold\" --force-yes"
169.46.88.66       version "3.2.7"
169.46.88.66     end

**Comment by josephholsten** [comment]
This repo is EOL, but the code lives on at https://github.com/sous-chefs/mongodb. Could you give that cookbook a look and let us know if it doesn't fix your issue?
