### ISSUE TITLE
Install fails with Librarian and Vagrant.

### ISSUE THREAD

**Issue by antoinelyset** [edelight/chef-mongodb#86]
Hi,

I just have a regular Vagrant and Librarian config but I can get MongoDB to work. If I understand it well. I think Chef tries to restart mongod but it doesn't succeed resulting in an error.

My Vagrantfile : 

``` ruby
Vagrant::Config.run do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"
  config.vm.host_name = 'vagrant'
  config.vm.forward_port 3000, 3000

  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "mongodb::default"
  end
```

My Cheffile :

``` ruby
#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'mongodb'
```

The log on install : 

``` bash
STDOUT: ** Running mongodb (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/mongodb.log)
 * Starting database mongodb
   ...fail!
STDERR: 
---- End output of /etc/init.d/mongodb start ----
Ran /etc/init.d/mongodb start returned 1; ignore_failure is set, continuing

================================================================================

Error executing action `start` on resource 'service[mongodb]'

================================================================================


Mixlib::ShellOut::ShellCommandFailed

------------------------------------

Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/mongodb start ----
STDOUT: ** Running mongodb (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/mongodb.log)
 * Starting database mongodb
   ...fail!
STDERR: 
---- End output of /etc/init.d/mongodb start ----
Ran /etc/init.d/mongodb start returned 1


Resource Declaration:

---------------------

# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/definitions/mongodb.rb

116:   # service
117:   service name do
118:     supports :status => true, :restart => true
119:     action service_action
120:     notifies service_notifies
121:     if !replicaset_name.nil?
122:       notifies :create, "ruby_block[config_replicaset]"
123:     end
124:     if type == "mongos"

Compiled Resource:

------------------

# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/definitions/mongodb.rb:117:in `from_file'

service("mongodb") do
  service_name "mongodb"
  params {:replicaset=>nil, :action=>[:enable, :start], :port=>27017, :mongodb_type=>"mongod", :dbpath=>"/var/lib/mongodb", :name=>"mongodb", :logpath=>"/var/log/mongodb", :configfile=>"/etc/mongodb.conf", :configserver=>[], :notifies=>[]}
  retry_delay 2
  retries 0
  recipe_name "default"
  pattern "mongodb"
  ignore_failure true
  action [:enable, :start]
  cookbook_name :mongodb
  startup_type :automatic
  supports {:status=>true, :restart=>true}
end
```

The log in /var/log/mongodb/mongodb.log : 

``` bash
Mon Feb  4 21:07:51 
Mon Feb  4 21:07:51 warning: 32-bit servers don't have journaling enabled by default. Please use --journal if you want durability.
Mon Feb  4 21:07:51 
Mon Feb  4 21:07:51 [initandlisten] MongoDB starting : pid=1789 port=27017 dbpath=/var/lib/mongodb 32-bit host=vagrant
Mon Feb  4 21:07:51 [initandlisten] 
Mon Feb  4 21:07:51 [initandlisten] ** NOTE: when using MongoDB 32 bit, you are limited to about 2 gigabytes of data
Mon Feb  4 21:07:51 [initandlisten] **       see http://blog.mongodb.org/post/137788967/32-bit-limitations
Mon Feb  4 21:07:51 [initandlisten] **       with --journal, the limit is lower
Mon Feb  4 21:07:51 [initandlisten] 
Mon Feb  4 21:07:51 [initandlisten] db version v2.0.4, pdfile version 4.5
Mon Feb  4 21:07:51 [initandlisten] git version: nogitversion
Mon Feb  4 21:07:51 [initandlisten] build info: Linux roseapple 2.6.24-28-server #1 SMP Wed Aug 18 21:17:51 UTC 2010 i686 BOOST_LIB_VERSION=1_46_1
Mon Feb  4 21:07:51 [initandlisten] options: { dbpath: "/var/lib/mongodb", logpath: "/var/log/mongodb/mongodb.log", port: 27017 }
Mon Feb  4 21:07:51 [initandlisten] exception in initAndListen: 10310 Unable to acquire lock for lockfilepath: /var/lib/mongodb/mongod.lock, terminating
Mon Feb  4 21:07:51 dbexit: 
Mon Feb  4 21:07:51 [initandlisten] shutdown: going to close listening sockets...
Mon Feb  4 21:07:51 [initandlisten] shutdown: going to flush diaglog...
Mon Feb  4 21:07:51 [initandlisten] shutdown: going to close sockets...
Mon Feb  4 21:07:51 [initandlisten] shutdown: waiting for fs preallocator...
Mon Feb  4 21:07:51 [initandlisten] shutdown: closing all files...
Mon Feb  4 21:07:51 [initandlisten] closeAllFiles() finished
Mon Feb  4 21:07:51 dbexit: really exiting now
Mon Feb  4 21:11:56 [clientcursormon] mem (MB) res:12 virt:88 mapped:0
```

**Comment by miketheman** [comment]
Does `/var/lib/mongodb/` exist on the VM?

**Comment by antoinelyset** [comment]
Yes : 

```
vagrant@vagrant:~$ ls  /var/lib/mongodb/
journal  mongod.lock
```

**Comment by miketheman** [comment]
Reason I ask is from the log file, you see:

``` console
Mon Feb  4 21:07:51 [initandlisten] exception in initAndListen: 10310 Unable to acquire lock for lockfilepath: /var/lib/mongodb/mongod.lock, terminating
Mon Feb  4 21:07:51 dbexit: 
```

Is mongo already running?

**Comment by antoinelyset** [comment]
Yes, and I think this is the problem. The recipe relaunchs it even if it is already running. I used the "standard" install, did I miss something ?

**Comment by rcarragher** [comment]
Yeah - having the same problem, but it's not on Vagrant, it's on ec2. The default definition starts mongodb, even though it's already started.  It looks like the service start _should_ return success (after a quick review of the init file) in this case, but it returns an error.  All subsequent chef runs fail as well, unless I manually stop mongodb. I'm going to spend a little bit more time trying to figure it out, but if anyone has ideas, would be very much appreciated.

**Comment by jer** [comment]
I am having this issue as well, in Ubuntu 12.04. It looks to me like the recipe is attempting to start mongodb with `/etc/init.d/mongodb start` while Ubuntu has already started the process with Upstart, ie `service mongodb start`

It has to be pretty easy to fix, although I'm not yet familiar enough with Chef to submit a patch.

**Comment by alexgorbatchev** [comment]
:+1: same issue with Ubuntu 12.04 server

**Comment by alexgraul** [comment]
Have the same issue with Ubuntu.

**Comment by andrewryno** [comment]
Same problem with Vagrant. I applied the patch in #90 to make it work with my install of Chef (11.4.4). It appears that it could be related?

**Comment by fmquaglia** [comment]
Same problem here with Vagrant and Uubuntu 12.04 64bits

**Comment by aleksblendwerk** [comment]
I think this only comes up when you use the **ubuntu-upstart** packages from the 10gen repo (as described in the 10gen installation notes) which I was grabbing via another cookbook. I just changed my Vagrantfile to let the mongodb cookbook take care of the packages (which is getting the **debian-sysvinit** package instead) with its own supplied recipe before running the default recipe and I am not getting any more errors: 

```
    chef.add_recipe "mongodb::10gen_repo"
    chef.add_recipe "mongodb"
```

Maybe this helps others running into this.

**Comment by jamesonjlee** [comment]
the 'bug' on ubuntu is that when we overwrite the package provided init.d script, the cookbook installed init.d doesn't deal with the old package installer.

**Comment by CMCDragonkai** [comment]
I'm getting this error as well currently. Here's my log file from vagrant up:

```
[2013-09-30T08:35:37+00:00] ERROR: service[mongodb] (mongodb::default line 117) had an error: Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/mongodb restart ----
STDOUT: ** Running mongodb (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/mongodb.log)
 * Restarting database mongodb
   ...fail!
STDERR:
---- End output of /etc/init.d/mongodb restart ----
Ran /etc/init.d/mongodb restart returned 1; ignore_failure is set, continuing

================================================================================
Error executing action `restart` on resource 'service[mongodb]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /etc/init.d/mongodb restart ----
STDOUT: ** Running mongodb (/usr/bin/mongod  --port 27017 --dbpath /var/lib/mongodb --logpath /var/log/mongodb/mongodb.log)
 * Restarting database mongodb
   ...fail!
STDERR:
---- End output of /etc/init.d/mongodb restart ----
Ran /etc/init.d/mongodb restart returned 1

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/definitions/mongodb.rb

116:   # service
117:   service name do
118:     supports :status => true, :restart => true
119:     action service_action
120:     notifies service_notifies
121:     if !replicaset_name.nil?
122:       notifies :create, "ruby_block[config_replicaset]"
123:     end
124:     if type == "mongos"

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-1/chef-solo-1/cookbooks/mongodb/definitions/mongodb.rb:117:in `from_file'

service("mongodb") do
  service_name "mongodb"
  params {:mongodb_type=>"mongod", :action=>[:enable, :start], :port=>"27017", :configfile=>"/etc/mongodb.conf", :configserver=>[], :replicaset=>nil, :dbpath=>"/var/lib/mongodb", :name=>"mongodb", :logpath=>"/var/log/mongodb", :notifies=>[]}
  retry_delay 2
  retries 0
  recipe_name "default"
  updated true
  pattern "mongodb"
  ignore_failure true
  action [:enable, :start]
  cookbook_name :mongodb
  startup_type :automatic
  supports {:status=>true, :restart=>true}
end

[2013-09-30T08:35:37+00:00] INFO: Chef Run complete in 919.958821 seconds
[2013-09-30T08:35:37+00:00] INFO: Running report handlers
[2013-09-30T08:35:37+00:00] INFO: Report handlers complete
```

The vagrantfile was taken from Rove.io, and ran on Windows 8

**Comment by jamesonjlee** [comment]
does it work if you re-run the vagrant's configuration phase (without destroying the vagrant instance)?

**Comment by jamesonjlee** [comment]
now fixed

**Comment by ringular** [comment]
Hey all, I'm having the same issue with version `0.15.0`, Any ideas?

```
Compiling Cookbooks...
[2014-02-25T06:31:34+00:00] WARN: CentOS doesn't provide mongodb, forcing use of 10gen repo
Recipe: build-essential::rhel
  * package[autoconf] action install (up to date)
  * package[bison] action install (up to date)
  * package[flex] action install (up to date)
  * package[gcc] action install (up to date)
  * package[gcc-c++] action install (up to date)
  * package[kernel-devel] action install (up to date)
  * package[make] action install (up to date)
  * package[m4] action install (up to date)
Recipe: aws::default
  * chef_gem[right_aws] action install (up to date)
Recipe: mongodb::mongo_gem
  * chef_gem[mongo] action install (up to date)
  * chef_gem[bson_ext] action install (up to date)
[2014-02-25T06:31:38+00:00] WARN: Cloning resource attributes for template[/etc/mongodb.conf] from prior resource (CHEF-3694)
[2014-02-25T06:31:38+00:00] WARN: Previous template[/etc/mongodb.conf]: /var/chef/cache/cookbooks/mongodb/recipes/install.rb:21:in `from_file'
[2014-02-25T06:31:38+00:00] WARN: Current  template[/etc/mongodb.conf]: /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:137:in `block in from_file'
[2014-02-25T06:31:38+00:00] WARN: Cloning resource attributes for template[/etc/init.d/mongod] from prior resource (CHEF-3694)
[2014-02-25T06:31:38+00:00] WARN: Previous template[/etc/init.d/mongod]: /var/chef/cache/cookbooks/mongodb/recipes/install.rb:42:in `from_file'
[2014-02-25T06:31:38+00:00] WARN: Current  template[/etc/init.d/mongod]: /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:170:in `block in from_file'
Converging 27 resources
Recipe: build-essential::rhel
  * package[autoconf] action nothing (skipped due to action :nothing)
  * package[bison] action nothing (skipped due to action :nothing)
  * package[flex] action nothing (skipped due to action :nothing)
  * package[gcc] action nothing (skipped due to action :nothing)
  * package[gcc-c++] action nothing (skipped due to action :nothing)
  * package[kernel-devel] action nothing (skipped due to action :nothing)
  * package[make] action nothing (skipped due to action :nothing)
  * package[m4] action nothing (skipped due to action :nothing)
Recipe: database::aws_ebs
  * directory[/data] action create (up to date)
Recipe: aws::default
  * chef_gem[right_aws] action install (up to date)
Recipe: database::aws_ebs
  * aws_ebs_volume[data_volume] action create (up to date)
  * aws_ebs_volume[data_volume] action attach (up to date)
  * ruby_block[sleeping_data_volume] action run
    - execute the ruby block sleeping_data_volume

  * execute[mkfs] action run (skipped due to not_if)
  * mount[/data] action mount (up to date)
  * mount[/data] action enable (up to date)
Recipe: mongodb::10gen_repo
  * yum_repository[10gen] action addRecipe: <Dynamically Defined Resource>
  * template[/etc/yum.repos.d/10gen.repo] action create (up to date)
  * execute[yum-makecache-10gen] action nothing (skipped due to action :nothing)
  * ruby_block[yum-cache-reload-10gen] action nothing (skipped due to action :nothing)
 (up to date)
Recipe: mongodb::install
  * file[/etc/sysconfig/mongodb] action create_if_missing (up to date)
  * template[/etc/mongodb.conf] action create_if_missing (up to date)
  * template[/etc/init.d/mongod] action create_if_missing (up to date)
  * package[mongo-10gen-server] action install (up to date)
Recipe: mongodb::mongo_gem
  * chef_gem[mongo] action install (up to date)
  * chef_gem[bson_ext] action install (up to date)
Recipe: mongodb::replicaset
  * template[/etc/sysconfig/mongodb] action create (up to date)
  * template[/etc/mongodb.conf] action create (up to date)
  * directory[/var/log/mongodb] action create (up to date)
  * directory[/data/mongodb] action create (up to date)
  * template[/etc/init.d/mongod] action create (up to date)
  * service[mongod] action enable (up to date)
  * service[mongod] action start
================================================================================
Error executing action `start` on resource 'service[mongod]'
================================================================================


Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service mongod start ----
STDOUT: Starting mongod: warning: remove or comment out this line by starting it with '#', skipping now : nojournal = false
warning: remove or comment out this line by starting it with '#', skipping now : rest = false
warning: bind_ip of 0.0.0.0 is unnecessary; listens on all ips by default
about to fork child process, waiting until server is ready for connections.
forked process: 19426
all output going to: /var/log/mongodb/mongodb.log
ERROR: child process failed, exited with error number 100
[FAILED]
STDERR:
---- End output of /sbin/service mongod start ----
Ran /sbin/service mongod start returned 1


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb

187:   service new_resource.name do
188:     provider Chef::Provider::Service::Upstart if node['mongodb']['apt_repo'] == 'ubuntu-upstart'
189:     supports :status => true, :restart => true
190:     action new_resource.service_action
191:     new_resource.service_notifies.each do |service_notify|
192:       notifies :run, service_notify
193:     end
194:     notifies :create, 'ruby_block[config_replicaset]' if new_resource.is_replicaset && new_resource.auto_configure_replicaset
195:     notifies :create, 'ruby_block[config_sharding]', :immediately if new_resource.type == 'mongos' && new_resource.auto_configure_sharding
196:       # we don't care about a running mongodb service in these cases, all we need is stopping it
197:     ignore_failure true if new_resource.name == 'mongodb'
198:   end
199:
200:   # replicaset
201:   if new_resource.is_replicaset && new_resource.auto_configure_replicaset
202:     rs_nodes = search(
203:       :node,
204:       "mongodb_cluster_name:#{new_resource.replicaset['mongodb']['cluster_name']} AND \
205:        mongodb_is_replicaset:true AND \
206:        mongodb_shard_name:#{new_resource.replicaset['mongodb']['shard_name']} AND \
207:        chef_environment:#{new_resource.replicaset.chef_environment}"
208:     )
209:
210:     ruby_block 'config_replicaset' do
211:       block do
212:         MongoDB.configure_replicaset(new_resource.replicaset, replicaset_name, rs_nodes) unless new_resource.replicaset.nil?
213:       end
214:       action :nothing
215:     end
216:
217:     ruby_block 'run_config_replicaset' do
218:       block {}
219:       notifies :create, 'ruby_block[config_replicaset]'
220:     end
221:   end
222:



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/mongodb/definitions/mongodb.rb:187:in `block in from_file'

service("mongod") do
  params {:mongodb_type=>"mongod", :action=>[:enable, :start], :logpath=>"/var/log/mongodb/mongodb.log", :dbpath=>"/data/mongodb", :configservers=>[], :replicaset=>node[5-database], :notifies=>[], :port=>27017, :enable_rest=>false, :smallfiles=>true, :name=>"mongod"}
  action [:enable, :start]
  supports {:status=>true, :restart=>true}
  retries 0
  retry_delay 2
  service_name "mongod"
  enabled true
  pattern "mongod"
  startup_type :automatic
  cookbook_name "mongodb"
  recipe_name "replicaset"
end



[2014-02-25T06:31:43+00:00] ERROR: Running exception handlers
[2014-02-25T06:31:43+00:00] ERROR: Exception handlers complete
[2014-02-25T06:31:43+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 1 resources updated
[2014-02-25T06:31:43+00:00] ERROR: service[mongod] (mongodb::replicaset line 187) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/service mongod start ----
STDOUT: Starting mongod: warning: remove or comment out this line by starting it with '#', skipping now : nojournal = false
warning: remove or comment out this line by starting it with '#', skipping now : rest = false
warning: bind_ip of 0.0.0.0 is unnecessary; listens on all ips by default
about to fork child process, waiting until server is ready for connections.
forked process: 19426
all output going to: /var/log/mongodb/mongodb.log
ERROR: child process failed, exited with error number 100
[FAILED]
STDERR:
---- End output of /sbin/service mongod start ----
Ran /sbin/service mongod start returned 1
[2014-02-25T06:31:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Mongo Logs:

```
***** SERVER RESTARTED *****


Tue Feb 25 06:31:43.651 [initandlisten] MongoDB starting : pid=19426 port=27017 dbpath=/data/mongodb 64-bit host=ip-10-0-0-241
Tue Feb 25 06:31:43.652 [initandlisten] db version v2.4.6
Tue Feb 25 06:31:43.652 [initandlisten] git version: b9925db5eac369d77a3a5f5d98a145eaaacd9673
Tue Feb 25 06:31:43.652 [initandlisten] build info: Linux ip-10-2-29-40 2.6.21.7-2.ec2.v1.2.fc8xen #1 SMP Fri Nov 20 17:48:28 EST 2009 x86_64 BOOST_LIB_VERSION=1_49
Tue Feb 25 06:31:43.652 [initandlisten] allocator: tcmalloc
Tue Feb 25 06:31:43.652 [initandlisten] options: { bind_ip: "0.0.0.0", config: "/etc/mongodb.conf", dbpath: "/data/mongodb", fork: "true", logappend: "true", logpath: "/var/log/mongodb/mongodb.log", pidfilepath: "/var/run/mongodb/mongod.pid", port: 27017, replSet: "rs0", smallfiles: "true" }
Tue Feb 25 06:31:43.652 [initandlisten] exception in initAndListen: 10310 Unable to lock file: /data/mongodb/mongod.lock. Is a mongod instance already running?, terminating
Tue Feb 25 06:31:43.652 dbexit:
Tue Feb 25 06:31:43.652 [initandlisten] shutdown: going to close listening sockets...
Tue Feb 25 06:31:43.652 [initandlisten] shutdown: going to flush diaglog...
Tue Feb 25 06:31:43.652 [initandlisten] shutdown: going to close sockets...
Tue Feb 25 06:31:43.653 [initandlisten] shutdown: waiting for fs preallocator...
Tue Feb 25 06:31:43.653 [initandlisten] shutdown: lock for final commit...
Tue Feb 25 06:31:43.653 [initandlisten] shutdown: final commit...
Tue Feb 25 06:31:43.653 [initandlisten] shutdown: closing all files...
Tue Feb 25 06:31:43.653 [initandlisten] closeAllFiles() finished
Tue Feb 25 06:31:43.653 dbexit: really exiting now
```

**Comment by jspiewak** [comment]
What is the ownership and permissions of /data/mongodb ?

**Comment by ringular** [comment]
owner & group: mongod with 755

**Comment by cvakiitho** [comment]
In case someone stumbles to ringular issue in future, I fixed that by uninstalling mongodb-org from my centos, not sure why it was installed in first place, but `yum erase mongodb-org` got it fixed.
